import type { AssetTemplate } from '../types';

export const ASSET_TEMPLATES: AssetTemplate[] = [
  // === Produktion ===
  {
    id: 'montagearbeitsplatz',
    label: 'Montagearbeitsplatz',
    category: 'Produktion',
    icon: '🔧',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 2.0, height: 0.9, depth: 0.7 } },
    defaultColor: '#5c6bc0',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.6, metalness: 0.2 },
    defaultMetadata: { name: 'Montagearbeitsplatz', description: 'Arbeitstisch mit Bildschirm' },
    tags: ['arbeit', 'tisch', 'montage'],
  },
  {
    id: 'produktionslinie',
    label: 'Produktionslinie',
    category: 'Produktion',
    icon: '🏭',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 6.0, height: 1.2, depth: 0.8 } },
    defaultColor: '#37474f',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.5, metalness: 0.4 },
    defaultMetadata: { name: 'Produktionslinie', description: 'Langes Fließband' },
    tags: ['band', 'fließband', 'linie'],
  },
  {
    id: 'cnc-maschine',
    label: 'CNC-Maschine',
    category: 'Produktion',
    icon: '⚙️',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 1.5, height: 1.8, depth: 1.5 } },
    defaultColor: '#455a64',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.4, metalness: 0.6 },
    defaultMetadata: { name: 'CNC-Maschine', description: 'Kompaktmaschine' },
    tags: ['maschine', 'cnc', 'fräse'],
  },
  {
    id: 'roboterarm',
    label: 'Roboterarm',
    category: 'Produktion',
    icon: '🤖',
    isUserAsset: false,
    geometry: { kind: 'cylinder', params: { radiusTop: 0.2, radiusBottom: 0.4, height: 2.0 } },
    defaultColor: '#ff6f00',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.3, metalness: 0.7 },
    defaultMetadata: { name: 'Roboterarm', description: 'Industrieroboter' },
    tags: ['roboter', 'arm', 'automatisierung'],
  },
  {
    id: 'pruefstation',
    label: 'Prüfstation',
    category: 'Produktion',
    icon: '🔍',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 1.0, height: 1.5, depth: 0.8 } },
    defaultColor: '#1565c0',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.5, metalness: 0.3 },
    defaultMetadata: { name: 'Prüfstation', description: 'Qualitätsprüfungs-Arbeitsplatz' },
    tags: ['prüfung', 'qualität', 'test'],
  },
  {
    id: 'schweissanlage',
    label: 'Schweißanlage',
    category: 'Produktion',
    icon: '🔥',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 1.2, height: 2.0, depth: 1.2 } },
    defaultColor: '#d84315',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.5, metalness: 0.5 },
    defaultMetadata: { name: 'Schweißanlage', description: 'Schweißstation' },
    tags: ['schweißen', 'schweiss', 'anlage'],
  },
  {
    id: 'montagebock',
    label: 'Montagebock',
    category: 'Produktion',
    icon: '🪑',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 0.8, height: 0.6, depth: 0.8 } },
    defaultColor: '#6d4c41',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.7, metalness: 0.1 },
    defaultMetadata: { name: 'Montagebock', description: 'Kleines Tischelement' },
    tags: ['bock', 'tisch', 'klein'],
  },

  // === Logistik ===
  {
    id: 'regalblock',
    label: 'Regalblock',
    category: 'Logistik',
    icon: '📦',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 4.0, height: 2.5, depth: 1.0 } },
    defaultColor: '#78909c',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.6, metalness: 0.3 },
    defaultMetadata: { name: 'Regalblock', description: 'Hohes Lagerregal' },
    tags: ['regal', 'lager', 'block'],
  },
  {
    id: 'palette',
    label: 'Palette',
    category: 'Logistik',
    icon: '🪵',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 1.2, height: 0.15, depth: 0.8 } },
    defaultColor: '#8d6e63',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.9, metalness: 0.0 },
    defaultMetadata: { name: 'Palette', description: 'Europalette' },
    tags: ['palette', 'euro', 'holz'],
  },
  {
    id: 'kiste-klein',
    label: 'Kiste (klein)',
    category: 'Logistik',
    icon: '📫',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 0.4, height: 0.3, depth: 0.4 } },
    defaultColor: '#a1887f',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.8, metalness: 0.0 },
    defaultMetadata: { name: 'Kiste (klein)', description: 'Transportbox' },
    tags: ['kiste', 'box', 'klein'],
  },
  {
    id: 'kiste-gross',
    label: 'Kiste (groß)',
    category: 'Logistik',
    icon: '📦',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 1.0, height: 0.8, depth: 0.8 } },
    defaultColor: '#795548',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.8, metalness: 0.0 },
    defaultMetadata: { name: 'Kiste (groß)', description: 'Großer Behälter' },
    tags: ['kiste', 'box', 'gross'],
  },
  {
    id: 'gabelstapler',
    label: 'Gabelstapler',
    category: 'Logistik',
    icon: '🚜',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 1.2, height: 2.0, depth: 2.5 } },
    defaultColor: '#f9a825',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.4, metalness: 0.5 },
    defaultMetadata: { name: 'Gabelstapler', description: 'Gabelstapler' },
    tags: ['stapler', 'gabel', 'fahrzeug'],
  },
  {
    id: 'hubwagen',
    label: 'Hubwagen',
    category: 'Logistik',
    icon: '🛒',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 0.6, height: 0.4, depth: 1.5 } },
    defaultColor: '#f57f17',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.4, metalness: 0.5 },
    defaultMetadata: { name: 'Hubwagen', description: 'Handgabelhubwagen' },
    tags: ['hubwagen', 'hand', 'transport'],
  },
  {
    id: 'container-stahl',
    label: 'Container (Stahl)',
    category: 'Logistik',
    icon: '🚢',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 6.0, height: 2.6, depth: 2.4 } },
    defaultColor: '#1b5e20',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.5, metalness: 0.6 },
    defaultMetadata: { name: 'Container (Stahl)', description: 'ISO-Seecontainer' },
    tags: ['container', 'stahl', 'iso'],
  },

  // === Büro & Verwaltung ===
  {
    id: 'buerotisch',
    label: 'Bürotisch',
    category: 'Büro & Verwaltung',
    icon: '🖥️',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 1.6, height: 0.75, depth: 0.8 } },
    defaultColor: '#eceff1',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.6, metalness: 0.1 },
    defaultMetadata: { name: 'Bürotisch', description: 'Einzeltisch' },
    tags: ['büro', 'tisch', 'schreibtisch'],
  },
  {
    id: 'buerostuhl',
    label: 'Bürostuhl',
    category: 'Büro & Verwaltung',
    icon: '💺',
    isUserAsset: false,
    geometry: { kind: 'cylinder', params: { radiusTop: 0.25, radiusBottom: 0.25, height: 1.0 } },
    defaultColor: '#263238',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.7, metalness: 0.2 },
    defaultMetadata: { name: 'Bürostuhl', description: 'Drehstuhl' },
    tags: ['stuhl', 'büro', 'sitzen'],
  },
  {
    id: 'schrank',
    label: 'Schrank',
    category: 'Büro & Verwaltung',
    icon: '🗄️',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 1.0, height: 2.0, depth: 0.5 } },
    defaultColor: '#90a4ae',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.5, metalness: 0.3 },
    defaultMetadata: { name: 'Schrank', description: 'Aktenschrank' },
    tags: ['schrank', 'akten', 'möbel'],
  },
  {
    id: 'besprechungstisch',
    label: 'Besprechungstisch',
    category: 'Büro & Verwaltung',
    icon: '🪑',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 2.4, height: 0.75, depth: 1.2 } },
    defaultColor: '#4e342e',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.4, metalness: 0.1 },
    defaultMetadata: { name: 'Besprechungstisch', description: 'Konferenztisch' },
    tags: ['tisch', 'besprechung', 'konferenz'],
  },
  {
    id: 'whiteboard',
    label: 'Whiteboard',
    category: 'Büro & Verwaltung',
    icon: '📋',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 1.8, height: 1.2, depth: 0.05 } },
    defaultColor: '#fafafa',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.2, metalness: 0.0 },
    defaultMetadata: { name: 'Whiteboard', description: 'Wandtafel' },
    tags: ['whiteboard', 'tafel', 'wand'],
  },

  // === Personal ===
  {
    id: 'mitarbeiter-stehend',
    label: 'Mitarbeiter (stehend)',
    category: 'Personal',
    icon: '🧑',
    isUserAsset: false,
    geometry: { kind: 'cylinder', params: { radiusTop: 0.15, radiusBottom: 0.2, height: 1.75 } },
    defaultColor: '#42a5f5',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.8, metalness: 0.0 },
    defaultMetadata: { name: 'Mitarbeiter (stehend)', description: 'Stehende Person' },
    tags: ['person', 'mitarbeiter', 'stehend'],
  },
  {
    id: 'mitarbeiter-sitzend',
    label: 'Mitarbeiter (sitzend)',
    category: 'Personal',
    icon: '🧑‍💻',
    isUserAsset: false,
    geometry: { kind: 'cylinder', params: { radiusTop: 0.2, radiusBottom: 0.2, height: 1.2 } },
    defaultColor: '#66bb6a',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.8, metalness: 0.0 },
    defaultMetadata: { name: 'Mitarbeiter (sitzend)', description: 'Sitzende Person' },
    tags: ['person', 'mitarbeiter', 'sitzend'],
  },

  // === Zonen ===
  {
    id: 'zone-produktion',
    label: 'Zone: Produktion',
    category: 'Zonen',
    icon: '🟥',
    isUserAsset: false,
    geometry: { kind: 'plane', params: { width: 10, height: 10 } },
    defaultColor: '#E53935',
    defaultScale: [1, 1, 1],
    defaultVisual: { opacity: 0.45, roughness: 1, metalness: 0 },
    defaultMetadata: { name: 'Produktion', zoneType: 'Produktion' },
    tags: ['zone', 'produktion', 'rot'],
  },
  {
    id: 'zone-logistik',
    label: 'Zone: Logistik',
    category: 'Zonen',
    icon: '🟩',
    isUserAsset: false,
    geometry: { kind: 'plane', params: { width: 10, height: 10 } },
    defaultColor: '#43A047',
    defaultScale: [1, 1, 1],
    defaultVisual: { opacity: 0.45, roughness: 1, metalness: 0 },
    defaultMetadata: { name: 'Logistik', zoneType: 'Logistik' },
    tags: ['zone', 'logistik', 'grün'],
  },
  {
    id: 'zone-buero',
    label: 'Zone: Büro',
    category: 'Zonen',
    icon: '🟦',
    isUserAsset: false,
    geometry: { kind: 'plane', params: { width: 10, height: 10 } },
    defaultColor: '#1E88E5',
    defaultScale: [1, 1, 1],
    defaultVisual: { opacity: 0.45, roughness: 1, metalness: 0 },
    defaultMetadata: { name: 'Büro', zoneType: 'Büro' },
    tags: ['zone', 'büro', 'blau'],
  },
  {
    id: 'zone-tpm',
    label: 'Zone: TPM',
    category: 'Zonen',
    icon: '🟪',
    isUserAsset: false,
    geometry: { kind: 'plane', params: { width: 10, height: 10 } },
    defaultColor: '#8E24AA',
    defaultScale: [1, 1, 1],
    defaultVisual: { opacity: 0.45, roughness: 1, metalness: 0 },
    defaultMetadata: { name: 'TPM / Wartung', zoneType: 'TPM' },
    tags: ['zone', 'tpm', 'wartung', 'lila'],
  },
  {
    id: 'zone-eingang',
    label: 'Zone: Eingang',
    category: 'Zonen',
    icon: '🟧',
    isUserAsset: false,
    geometry: { kind: 'plane', params: { width: 10, height: 10 } },
    defaultColor: '#FB8C00',
    defaultScale: [1, 1, 1],
    defaultVisual: { opacity: 0.45, roughness: 1, metalness: 0 },
    defaultMetadata: { name: 'Eingang', zoneType: 'Eingang' },
    tags: ['zone', 'eingang', 'orange'],
  },
  {
    id: 'zone-sicherheit',
    label: 'Zone: Sicherheit',
    category: 'Zonen',
    icon: '🟨',
    isUserAsset: false,
    geometry: { kind: 'plane', params: { width: 10, height: 10 } },
    defaultColor: '#F9A825',
    defaultScale: [1, 1, 1],
    defaultVisual: { opacity: 0.45, roughness: 1, metalness: 0 },
    defaultMetadata: { name: 'Sicherheitszone', zoneType: 'Sicherheit' },
    tags: ['zone', 'sicherheit', 'gelb'],
  },

  // === Wege & Markierungen ===
  {
    id: 'fahrweg',
    label: 'Fahrweg (breit)',
    category: 'Wege & Markierungen',
    icon: '🛣️',
    isUserAsset: false,
    geometry: { kind: 'plane', params: { width: 3, height: 8 } },
    defaultColor: '#fdd835',
    defaultScale: [1, 1, 1],
    defaultVisual: { opacity: 0.8, roughness: 1, metalness: 0 },
    defaultMetadata: { name: 'Fahrweg', description: 'Breiter Fahrweg, gelb' },
    tags: ['weg', 'fahren', 'gelb'],
  },
  {
    id: 'fussgaengerweg',
    label: 'Fußgängerweg',
    category: 'Wege & Markierungen',
    icon: '🚶',
    isUserAsset: false,
    geometry: { kind: 'plane', params: { width: 1, height: 8 } },
    defaultColor: '#ffffff',
    defaultScale: [1, 1, 1],
    defaultVisual: { opacity: 0.7, roughness: 1, metalness: 0 },
    defaultMetadata: { name: 'Fußgängerweg', description: 'Schmaler Fußweg, weiß' },
    tags: ['weg', 'fuss', 'weiss'],
  },
  {
    id: 'stopp-linie',
    label: 'Stopp-Linie',
    category: 'Wege & Markierungen',
    icon: '🛑',
    isUserAsset: false,
    geometry: { kind: 'plane', params: { width: 3, height: 0.3 } },
    defaultColor: '#e53935',
    defaultScale: [1, 1, 1],
    defaultVisual: { opacity: 0.9, roughness: 1, metalness: 0 },
    defaultMetadata: { name: 'Stopp-Linie', description: 'Rote Stopp-Markierung' },
    tags: ['stopp', 'linie', 'rot'],
  },

  // === Primitive ===
  {
    id: 'prim-box',
    label: 'Box',
    category: 'Primitive',
    icon: '⬜',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 1, height: 1, depth: 1 } },
    defaultColor: '#9e9e9e',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.5, metalness: 0.0 },
    defaultMetadata: { name: 'Box' },
    tags: ['box', 'würfel', 'quader'],
  },
  {
    id: 'prim-sphere',
    label: 'Kugel',
    category: 'Primitive',
    icon: '⚪',
    isUserAsset: false,
    geometry: { kind: 'sphere', params: { radius: 0.5 } },
    defaultColor: '#9e9e9e',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.5, metalness: 0.0 },
    defaultMetadata: { name: 'Kugel' },
    tags: ['kugel', 'sphere', 'rund'],
  },
  {
    id: 'prim-cylinder',
    label: 'Zylinder',
    category: 'Primitive',
    icon: '🔵',
    isUserAsset: false,
    geometry: { kind: 'cylinder', params: { radiusTop: 0.5, radiusBottom: 0.5, height: 1 } },
    defaultColor: '#9e9e9e',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.5, metalness: 0.0 },
    defaultMetadata: { name: 'Zylinder' },
    tags: ['zylinder', 'cylinder', 'rohr'],
  },
  {
    id: 'prim-cone',
    label: 'Kegel',
    category: 'Primitive',
    icon: '🔺',
    isUserAsset: false,
    geometry: { kind: 'cone', params: { radius: 0.5, height: 1 } },
    defaultColor: '#9e9e9e',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.5, metalness: 0.0 },
    defaultMetadata: { name: 'Kegel' },
    tags: ['kegel', 'cone', 'spitz'],
  },
  {
    id: 'prim-torus',
    label: 'Torus',
    category: 'Primitive',
    icon: '🟠',
    isUserAsset: false,
    geometry: { kind: 'torus', params: { radius: 0.5, tube: 0.15 } },
    defaultColor: '#9e9e9e',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.5, metalness: 0.0 },
    defaultMetadata: { name: 'Torus' },
    tags: ['torus', 'ring', 'donut'],
  },
  {
    id: 'prim-plane',
    label: 'Fläche',
    category: 'Primitive',
    icon: '⬛',
    isUserAsset: false,
    geometry: { kind: 'plane', params: { width: 2, height: 2 } },
    defaultColor: '#9e9e9e',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.5, metalness: 0.0 },
    defaultMetadata: { name: 'Fläche' },
    tags: ['fläche', 'plane', 'boden'],
  },

  // === Infrastruktur ===
  {
    id: 'saeule',
    label: 'Säule',
    category: 'Infrastruktur',
    icon: '🏛️',
    isUserAsset: false,
    geometry: { kind: 'cylinder', params: { radiusTop: 0.15, radiusBottom: 0.15, height: 6 } },
    defaultColor: '#bdbdbd',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.7, metalness: 0.1 },
    defaultMetadata: { name: 'Säule', description: 'Tragsäule' },
    tags: ['säule', 'stütze', 'pfeiler'],
  },
  {
    id: 'wand-segment',
    label: 'Wand-Segment',
    category: 'Infrastruktur',
    icon: '🧱',
    isUserAsset: false,
    geometry: { kind: 'box', params: { width: 3.0, height: 3.5, depth: 0.2 } },
    defaultColor: '#e0e0e0',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.8, metalness: 0.0 },
    defaultMetadata: { name: 'Wand-Segment', description: 'Innen-Trennwand' },
    tags: ['wand', 'trennwand', 'segment'],
  },
  {
    id: 'feuerloescher',
    label: 'Feuerlöscher',
    category: 'Infrastruktur',
    icon: '🧯',
    isUserAsset: false,
    geometry: { kind: 'cylinder', params: { radiusTop: 0.08, radiusBottom: 0.08, height: 0.6 } },
    defaultColor: '#c62828',
    defaultScale: [1, 1, 1],
    defaultVisual: { roughness: 0.4, metalness: 0.5 },
    defaultMetadata: { name: 'Feuerlöscher', description: 'Sicherheitsausrüstung' },
    tags: ['feuer', 'löscher', 'sicherheit'],
  },

  // === Schilder & Labels ===
  {
    id: 'text-label',
    label: 'Text-Label',
    category: 'Schilder & Labels',
    icon: '🏷️',
    isUserAsset: false,
    geometry: { kind: 'text', params: { fontSize: 1.2 } },
    defaultColor: '#ffffff',
    defaultScale: [1, 1, 1],
    defaultVisual: { opacity: 1, roughness: 1, metalness: 0 },
    defaultMetadata: { name: 'Neues Label', description: 'Schwebendes Billboard-Label' },
    tags: ['text', 'label', 'schild', 'beschriftung'],
  },
  {
    id: 'nummern-label',
    label: 'Nummern-Label',
    category: 'Schilder & Labels',
    icon: '🔢',
    isUserAsset: false,
    geometry: { kind: 'text', params: { fontSize: 2.0 } },
    defaultColor: '#fdd835',
    defaultScale: [1, 1, 1],
    defaultVisual: { opacity: 1, roughness: 1, metalness: 0 },
    defaultMetadata: { name: '01', description: 'Nummern-Label' },
    tags: ['nummer', 'zahl', 'label'],
  },
];
